[package]
name = "rox-chats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-http-request = "0.2.13"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
serde_json = "1.0"